export default {
  default: 'default',
  status: 'status',
  emailConfirm: 'emailConfirm',
  restore: 'restore',
  changePassword: 'changePassword',
  privacy: 'privacy',
  skills: 'skills',
  messageSend: 'messageSend',
  sendARequest: 'sendARequest',
  requestSend: 'requestSend',
  questAgreed: 'questAgreed',
  areYouSure: 'areYouSure',
  transactionSend: 'transactionSend',
  cardHasBeenAdded: 'cardHasBeenAdded',
  deposit: 'deposit',
  addCard: 'addCard',
  widthraw: 'widthraw',
  review: 'review',
  thanks: 'Thanks ',
  inviteSend: 'inviteSend',
  questCreated: 'questCreated',
  raiseViews: 'raiseViews',
  invitation: 'invitation',
  applyForAPension: 'applyForAPension',
  pensionIsRegistered: 'pensionIsRegistered',
  makeDeposit: 'makeDeposit',
  changePercent: 'changePercent',
};
