export default {
  default: 'default',
  status: 'status',
  emailConfirm: 'emailConfirm',
  restore: 'restore',
  changePassword: 'changePassword',
  privacy: 'privacy',
  skills: 'skills',
  messageSend: 'messageSend',
  sendARequest: 'sendARequest',
  requestSend: 'requestSend',
  questAgreed: 'questAgreed',
  areYouSure: 'areYouSure',
  review: 'review',
  thanks: 'Thanks ',
};
