export default {
  getWqtWbnbBurns: (state) => state.wqtWbnbBurns || '',
  getWqtWbnbMints: (state) => state.wqtWbnbMints || '',
  getWqtWbnbSwaps: (state) => state.wqtWbnbSwaps || '',
  getWqtWbnbTokenDay: (state) => state.wqtWbnbTokenDay || '',
  getTableWqtWbnbTokenDay: (state) => state.tableWqtWbnbTokenDay || '',
  getWqtWbnbTokenDayLast: (state) => state.wqtWbnbTokenDayLast || '',
  getWqtWethBurns: (state) => state.wqtWethBurns || '',
  getWqtWethMints: (state) => state.wqtWethMints || '',
  getWqtWethSwaps: (state) => state.wqtWethSwaps || '',
  getWqtWethTokenDay: (state) => state.wqtWethTokenDay || '',
  getTableWqtWethTokenDay: (state) => state.tableWqtWethTokenDay || '',
  getWqtWethTokenDayLast: (state) => state.wqtWethTokenDayLast || '',
  getSwapAddress: (state) => state.swapAddress || '',
  getCrosschainTokensData: (state) => state.crosschainTokensData || [],
};
