export default () => ({
  wqtWbnbBurns: {},
  wqtWbnbMints: {},
  wqtWbnbSwaps: {},
  wqtWbnbTokenDay: {},
  wqtWbnbTokenDayLast: {},
  wqtWethBurns: {},
  wqtWethMints: {},
  wqtWethSwaps: {},
  wqtWethTokenDay: {},
  wqtWethTokenDayLast: {},
  crosschainTokensData: [],
  tableWqtWbnbTokenDay: [],
  tableWqtWethTokenDay: [],
});
