export default {
  getStatusKYC: (state) => state.userData.statusKYC,
  getCurrentLang: (state) => state.currentLang,
  isAuth: (state) => !!state.tokens.access,
  accessToken: (state) => state.tokens.access,
  refreshToken: (state) => state.tokens.refresh,
  getUserData: (state) => state.userData,
  getTwoFACode: (state) => state.twoFACode,
  getVerificationCode: (state) => state.verificationCode,
  getUserWalletAddress: (state) => state.userData?.wallet?.address,
  getStatus2FA: (state) => state.userData.statusKYC,
  getStatusTotp: (state) => state.userData.totpIsActive,
  getAnotherUserData: (state) => state.anotherUserData,
  getUserRole: (state) => state.userData.role,
  getUserCurrentPosition: (state) => state.currentUserPosition,
  getImageData: (state) => state.userData.avatar?.url,
  getUserSecondMobileNumber: (state) => state.userData.additionalInfo.secondMobileNumber,
  getUserEmail: (state) => state.userData.email,
  getUserPortfolios: (state) => state.portfolios,
  getUserPortfolio: (state) => state.medias,
  getAllUserReviews: (state) => state.userReviews,
  getUser2FA: (state) => state.userEnable2FA,
  getUserReferralId: (state) => state.userData.affiliateUser.referralCodeId,
};
