export default () => ({
  tokens: {
    access: '',
    refresh: '',
  },
  userData: {},
  anotherUserData: {
    avatar: { url: '' },
    additionalInfo: {
      company: '',
      address: '',
      description: '',
      secondMobileNumber: { fullNumber: '' },
      educations: { length: 0 },
      workExperiences: { length: 0 },
    },
    phone: { fullNumber: '' },
    tempPhone: { fullNumber: '' },
    questsStatistic: { opened: 0 },
    ratingStatistic: { averageMark: 0, reviewCount: 0 },
    role: 'employer',
  },
  currentUserPosition: null,
  userRole: {},
  userDataPassword: {},
  userSendCode: {},
  imageLink: {},
  secretKey: '',
  confirmCode: '',
  totp: '',
  portfolios: {
    count: 0,
  },
  portfolio: {},
  medias: null,
  userReviews: {},
  userEnable2FA: {},
  userDisable2FA: {},
  user2FA: false,
  statisticData: {
    chatsStatistic: null,
    questsStatistic: null,
    ratingStatistic: null,
  },
  unreadChatsCount: 0,
});
