export default () => ({
  tokens: {
    access: '',
    refresh: '',
  },
  userData: {},
  anotherUserData: {},
  currentUserPosition: null,
  userRole: {},
  userDataPassword: {},
  userSendCode: {},
  imageLink: {},
  secretKey: '',
  confirmCode: '',
  totp: '',
  portfolios: {},
  portfolio: {},
  medias: null,
  userReviews: {},
  userEnable2FA: {},
  userDisable2FA: {},
  user2FA: false,
});
