export default {
  getUpdateTime: (state) => state.updateTime,
  getChatInfoInviteOnQuest: (state) => state.chatInfoInviteOnQuest,
  getEmployeeList: (state) => state.employeeList,
  getEmployeeCount: (state) => state.employeeCount,
  getCurrentWorker: (state) => state.currentWorker,
  getUserSpecializations: (state) => state.currentWorker?.userSpecializations,
  getQuestsStatistic: (state) => state.currentWorker?.questsStatistic,
  getRatingStatistic: (state) => state.currentWorker?.ratingStatistic,
  getInfoDataMode: (state) => state.infoDataMode,
  getAllQuests: (state) => state.allQuests.quests,
  getAllQuestsCount: (state) => state.allQuests.count,
  getQuest: (state) => state.quest,
  getQuestUser: (state) => state.quest?.user || '',
  getQuestUserAvatar: (state) => state.quest?.user?.avatar?.url || null,
  getQuestUserCompany: (state) => state.quest?.user?.additionalInfo?.company || '',
  getCurrentStepEditQuest: (state) => state.currentStepEditQuest || '',
  getCurrentStepCreateQuest: (state) => state.currentStepCreateQuest || '',
  getResponded: (state) => state.responded,
  getInvited: (state) => state.invited,
  getResponsesMy: (state) => state.responsesMy || '',
  getRespondOnQuest: (state) => state.respondOnQuest,
  getFilters: (state) => state.filters,
  getSelectedSpecializationsFilters: (state) => state.selectedSpecializationsFilters,
  getSelectedPriceFilter: (state) => state.selectedPriceFilter,
  getAssignedWorker: (state) => state.quest.assignedWorker,
  getAvailableQuests: (state) => state.availableQuests,
};
