export default {
  getChatInfoInviteOnQuest: (state) => state.chatInfoInviteOnQuest,
  getEmployeeList: (state) => state.employeeList,
  getEmployeeCount: (state) => state.employeeCount,
  getInfoDataMode: (state) => state.infoDataMode,
  getAllQuests: (state) => state.allQuests.quests,
  getAllQuestsCount: (state) => state.allQuests.count,
  getQuest: (state) => state.quest,
  getCurrentStepEditQuest: (state) => state.currentStepEditQuest,
  getResponded: (state) => state.responded,
  getInvited: (state) => state.invited,
  getRespondOnQuest: (state) => state.respondOnQuest,
  getFilters: (state) => state.filters,
  getSelectedSpecializationsFilters: (state) => state.selectedSpecializationsFilters,
  getSelectedPriceFilter: (state) => state.selectedPriceFilter,
  getAssignedWorker: (state) => state.quest.assignedWorker,
  getAvailableQuests: (state) => state.availableQuests,
};
