export default () => ({
  questListForInvitation: {},
  chatInfoInviteOnQuest: {},
  currentWorker: {},
  workersList: {},
  allQuests: {},
  quest: {},
  infoDataMode: '',
  userInfoQuests: {},
  questsLocation: {},
  starredQuests: {},
  responses: {},
  currentStepCreateQuest: 1,
  currentStepEditQuest: 1,
  mapBounds: {},
  mapCenter: {},
  filters: null,
  specializationsFilters: [],
  priceFilter: { from: null, to: null },
});
