// eslint-disable-next-line import/prefer-default-export
export const images = Object.freeze({
  WQT: require('~/assets/img/ui/wqt-logo.svg'),
  POLYGON: require('~/assets/img/ui/Polygon.svg'),
  ETH: require('~/assets/img/ui/eth_white.svg'),
  ETH_BLACK: require('~/assets/img/ui/ethereum.svg'),
  BNB: require('~/assets/img/ui/bnb_yellow.svg'),
  EMPTY_AVATAR: require('~/assets/img/app/avatar_empty.png'),
  ERROR: require('~/assets/img/ui/error.svg'),
  QUEST_CREATED: require('assets/img/ui/questCreated.svg'),
  QUEST_AGREED: require('~/assets/img/ui/questAgreed.svg'),
  SUCCESS: require('~/assets/img/ui/success.svg'),
  WARNING: require('~/assets/img/ui/warning.svg'),
  DOCUMENT: require('~/assets/img/ui/document.svg'),
  CARD_ADDED: require('assets/img/ui/cardHasBeenAdded.svg'),
  TRANSACTION_SEND: require('~/assets/img/ui/transactionSend.svg'),
  WQ_LOGO: require('assets/img/app/logo.svg'),
  EMAIL: require('assets/img/icons/email.svg'),
  PASSWORD: require('assets/img/icons/password.svg'),
  CLOSE: require('assets/img/ui/close.svg'),
  MESSAGE: require('assets/img/ui/message.svg'),
  MESSAGE_UNREAD: require('assets/img/ui/message_unread.svg'),
  NOTIFICATION_OUTLINE_RED_DOT: require('assets/img/ui/notification_outline_red_dot.svg'),
  CREDIT_CARD: require('assets/img/ui/creditCard.svg'),
  TELEGRAM: require('assets/img/icons/telegram.png'),
});
